# Generated by Django 5.1.1 on 2024-11-29 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realtors", "0003_alter_realtor_date_hired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realtor",
            name="top_seller",
        ),
    ]
