# Generated by Django 5.1 on 2024-09-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open_house',
            field=models.BooleanField(default=True),
        ),
    ]
