# Generated by Django 5.1.1 on 2024-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_alter_listing_maps_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(),
        ),
    ]
